"""Five

Revision ID: 82d4136115df
Revises: e09754b809a7
Create Date: 2021-10-28 14:34:38.124418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d4136115df'
down_revision = 'e09754b809a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
